---
- name: 02a Playbook to Add Common Criteria Policy
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clemea2025-devwks-2008/vaults/ciscolive.vault


  tasks:
    - name: 02a Task to Add Common Criteria Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <aaa>
                  <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <policy>COMMON-POLICY</policy>
                    <char-changes>3</char-changes>
                    <lower-case>1</lower-case>
                    <max-length>127</max-length>
                    <min-length>12</min-length>
                    <numeric-count>1</numeric-count>
                    <special-case>1</special-case>
                    <upper-case>1</upper-case>
                    <character-repetition>2</character-repetition>
                    <restrict-consecutive-letters/>
                  </common-criteria>
                </aaa>
              </native>
            </config>
