---
- name: 04a - Configure MACsec on Cat9300X TenGigabit1/0/1 Playbook using YANG Models
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
   - ~/clemea2025-devwks-2008/vaults/ciscolive.vault
   - ~/clemea2025-devwks-2008/vaults/encrypted-pass.vault

  tasks:
    - name: 04a1 Task to Shutdown the Interface
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <TenGigabitEthernet>
                    <name>1/0/1</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"/>
                  </TenGigabitEthernet>
                </interface>
              </native>
            </config>

    - name: 04a2 Task to Shutdown the Interface
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"/>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

    - name: 04b Task to Configure MKA PSK CKN and CAK
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <key>
                  <chain xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-crypto">
                    <name>MACSEC-KEY</name>
                    <macsec/>
                    <key>
                      <id>1234</id>
                      <cryptographic-algorithm-choice>
                        <macsec>aes-256-cmac</macsec>
                      </cryptographic-algorithm-choice>
                      <key-string>
                        <encryption>0</encryption>
                        <key>{{ macsec_psk }}</key>
                      </key-string>
                    </key>
                  </chain>
                </key>
              </native>
            </config>

    - name: 04c Task to Configure MKA Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <mka>
                  <policy xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                    <name>MKA_G-1-0-1</name>
                    <macsec-cipher-suite>gcm-aes-256</macsec-cipher-suite>
                  </policy>
                  <suppress xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                    <syslogs>
                      <sak-rekey>true</sak-rekey>
                    </syslogs>
                  </suppress>
                </mka>
              </native>
            </config>

    - name: 04d Task to Configure Interface Description
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <TenGigabitEthernet>
                    <name>1/0/1</name>
                    <description>MACsec Encrypted Link</description>
                  </TenGigabitEthernet>
                </interface>
              </native>
            </config>

    - name: 04e Task to Configure the Interface with the MKA Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <TenGigabitEthernet>
                    <name>1/0/1</name>
                    <mka xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                      <policy>
                        <name>MKA_G-1-0-1</name>
                      </policy>
                    </mka>
                  </TenGigabitEthernet>
                </interface>
              </native>
            </config>

    - name: 04f Task to Configure the Interface with the MKA Key
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <TenGigabitEthernet>
                    <name>1/0/1</name>
                    <mka xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mka">
                      <pre-shared-key>
                        <key-chain>
                          <name>MACSEC-KEY</name>
                        </key-chain>
                      </pre-shared-key>
                    </mka>
                  </TenGigabitEthernet>
                </interface>
              </native>
            </config>

#    - name: 04g Task to Configure MACsec Network Link on the Interface
#      ansible.netcommon.netconf_config:
#        xml: |
#            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
#              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
#                <interface>
#                  <TenGigabitEthernet>
#                    <name>1/0/1</name>
#                    <macsec-option xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-switch">
#                      <macsec>
#                        <network-link/>
#                      </macsec>
#                    </macsec-option>
#                  </TenGigabitEthernet>
#                </interface>
#              </native>
#            </config>


    - name: 04g Task to Configure MACsec Network Link on the Interface on the Cat9300X
      ansible.netcommon.netconf_config:
        xml: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <interface>
                <TenGigabitEthernet>
                  <name>1/0/1</name>
                  <macsec-option xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-switch">
                    <macsec>
                      <network-link/>
                    </macsec>
                  </macsec-option>
                </TenGigabitEthernet>
              </interface>
            </native>
          </config>
      register: result_macsec_cat9kx
      failed_when: false

    - name: 04g Task to Configure MACsec Network Link on the Interface
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <macsec-option xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-switch">
                      <macsec>
                        <network-link/>
                      </macsec>
                    </macsec-option>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>
      register: result_macsec_cat9k
      failed_when: false


    - name: 04h Task to No Shut Interface on the Cat9300X
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <TenGigabitEthernet>
                    <name>1/0/1</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete"/>
                  </TenGigabitEthernet>
                </interface>
              </native>
            </config>
      register: result_noshut_cat9kx
      failed_when: false

    - name: 04h Task to No Shut Interface
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete"/>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>
      register: result_noshut_cat9k
      failed_when: false
