---
- name: Upgrade or Downgrade IOS XE versions in Bundle Mode
  hosts: iosxe
  gather_facts: false
  connection: network_cli
  
  vars_files:
    - ~/clemea2025-devwks-2008/vaults/ciscolive.vault
  vars:
    boot_image: "cat9k_iosxe.17.09.04.SPA.bin"

  tasks:
    - name: 01a - Remove inactive installer files
      cisco.ios.ios_command:
        commands:
          - command: "install remove inactive"
            prompt: "files?"
            answer: "y"

    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


    - name: 01b - Copy IOS XE bin file from podadmin2
      cisco.ios.ios_command:
        commands:
          - command: "copy http://128.107.223.248/'{{ boot_image }}' flash:'{{ boot_image }}'"


    - name: 01 - Remove existing boot system configuration
      cisco.ios.ios_config:
        lines:
          - no boot system


    - name: 02 - Set new boot system image
      cisco.ios.ios_config:
        lines:
          - "boot system flash:{{ boot_image }}"
        # - "boot system flash:cat9k_iosxe.16.12.04.SPA.bin"


    - name: 03 - Save the running configuration
      cisco.ios.ios_command:
        commands:
          - write memory


    - name: 04 - Write erase the config so the switch comes up clean & ZTP
      cisco.ios.ios_command:
        commands:
          - command: "write erase"
            prompt: "confirm"
            answer: "y"

# This worked
#    - name: Reload the XE device
#      cisco.ios.ios_command:
#        commands:
#          - command: "reload"
#            prompt: "Proceed with reload\\? \\[confirm\\]"
#            answer: "\n"

    - name: 05 - Reload the XE device
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - "Save?"
              - "confirm"
            answer:
              - "y"
              - "y"
