---
- name: Upgrade or Downgrade IOS XE versions in Bundle Mode
  hosts: iosxe
  gather_facts: false
  connection: network_cli
  
  vars_files:
    - ~/clemea2025-devwks-2008/vaults/ciscolive.vault
  vars:
    boot_image: "cat9k_iosxe.17.12.04.SPA.bin"
    ansible_command_timeout: 1200

  tasks:
#    - name: Shut down interface Ten1/0/3
#      cisco.ios.ios_config:
#        lines:
#          - shutdown
#        parents: interface Ten1/0/3
#      ignore_errors: true

#    - name: Shut down interface Gig1/0/3
#      cisco.ios.ios_config:
#        lines:
#          - shutdown
#        parents: interface Gig1/0/3
#      ignore_errors: true

#    - name: Timmay HARD STOP this Playbook
#      ansible.builtin.meta: end_play


    - name: 01 - Remove inactive installer files
      cisco.ios.ios_command:
        commands:
          - command: "install remove inactive"
            prompt: "files?"
            answer: "y"


    - name: 02 - Copy IOS XE bin file from podadmin2
      cli_command:
        command: "copy http: flash:"
        check_all: true
        prompt:
          - "Address or name of remote host"
          - "Source filename \\[\\]?"
          - "Destination filename [{{ boot_image }}]?"
        answer:
          - "128.107.223.248"
          - "{{ boot_image }}"
          - "{{ boot_image }}"


    - name: 03 - Remove existing boot system configuration
      cisco.ios.ios_config:
        lines:
          - no boot system


    - name: 04 - Set new boot system image
      cisco.ios.ios_config:
        lines:
          - "boot system flash:/{{ boot_image }}"


    - name: 05 - Save the running configuration
      cisco.ios.ios_command:
        commands:
          - write memory


    - name: 06 - Write erase the config so the switch comes up clean & ZTP
      cisco.ios.ios_command:
        commands:
          - command: "write erase"
            prompt: "confirm"
            answer: "y"

# This works if only one prompt
#    - name: Reload the XE device
#      cisco.ios.ios_command:
#        commands:
#          - command: "reload"
#            prompt: "Proceed with reload\\? \\[confirm\\]"
#            answer: "\n"

    - name: 07 - Reload the XE device
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - "Save?"
              - "confirm"
            answer:
              - "y"
              - "y"

#    - name: Timmay HARD STOP this Playbook
#      ansible.builtin.meta: end_play
